/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppGithub: typeof import('./src/components/AppGithub.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AppLocaleSwitch: typeof import('./src/components/AppLocaleSwitch.vue')['default']
    AppThemeSwitch: typeof import('./src/components/AppThemeSwitch.vue')['default']
    HomeView: typeof import('./src/components/HomeView.vue')['default']
    VarAppBar: typeof import('@varlet/ui')['_AppBarComponent']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarCard: typeof import('@varlet/ui')['_CardComponent']
    VarCell: typeof import('@varlet/ui')['_CellComponent']
    VarDivider: typeof import('@varlet/ui')['_DividerComponent']
    VarIcon: typeof import('@varlet/ui')['_IconComponent']
    VarImage: typeof import('@varlet/ui')['_ImageComponent']
    VarLink: typeof import('@varlet/ui')['_LinkComponent']
    VarMenu: typeof import('@varlet/ui')['_MenuComponent']
    VarOverlay: typeof import('@varlet/ui')['_OverlayComponent']
    VarPaper: typeof import('@varlet/ui')['_PaperComponent']
    VarProgress: typeof import('@varlet/ui')['_ProgressComponent']
    VarSpace: typeof import('@varlet/ui')['_SpaceComponent']
    VarTable: typeof import('@varlet/ui')['_TableComponent']
  }
}
